enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouGube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "anddea/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "anddea ReVanced"
patches-version = "v3.11.1-dev.1"
arch = "arm64-v8a"
build-mode = "module"
excluded-patches = "'GmsCore support'"
